# Generated by Django 4.0.3 on 2022-04-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
