# Generated by Django 4.0.3 on 2022-04-23 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_word_first_entry_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='attempts_brain',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
